In [1]:
import numpy as np

## NumPy Array

####  - How to create an empty and a full NumPy array?

In [2]:
np.empty([3,3])

array([[0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 6.107e-321],
       [0.000e+000, 0.000e+000, 0.000e+000]])

In [3]:
np.full([3,3], 50)

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

#### - Create a Numpy array filled with all zeros

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

#### - Create a Numpy array filled with all ones 

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

#### - Check whether a Numpy array contains a specified row 

In [6]:
arr = np.array([[5, 6, 5, 2, 4], [5, 8, 2, 0, 1], [15, 62, 22, 35, 42], [16, 8, 9, 15, 14]])
arr

array([[ 5,  6,  5,  2,  4],
       [ 5,  8,  2,  0,  1],
       [15, 62, 22, 35, 42],
       [16,  8,  9, 15, 14]])

In [7]:
[15, 62, 22, 35, 42] in arr.tolist()

True

####  - How to Remove rows in Numpy array that contains non-numeric values?

In [8]:
arr = np.array([[5, 6, 5], [5, 8, 2], [2, np.nan, np.nan]])
arr

array([[ 5.,  6.,  5.],
       [ 5.,  8.,  2.],
       [ 2., nan, nan]])

In [9]:
arr[~np.isnan(arr).any(axis=1)]

array([[5., 6., 5.],
       [5., 8., 2.]])

#### - Remove single-dimensional entries from the shape of an array

In [10]:
in_arr = np.array([[[5, 6, 5, 2], [5, 8, 2, 0]]])
in_arr.shape

(1, 2, 4)

In [11]:
out_arr = np.squeeze(in_arr)
out_arr.shape

(2, 4)

#### - Find the number of occurrences of a sequence in a NumPy array

In [12]:
arr = np.array([[6, 1, 6, 1], [6, 1, 6, 2], [6, 1, 5, 3], [2, 6, 1, 0]])
arr

array([[6, 1, 6, 1],
       [6, 1, 6, 2],
       [6, 1, 5, 3],
       [2, 6, 1, 0]])

In [13]:
repr(arr).count("6, 1")

5

#### - Find the most frequent value in a NumPy array 

In [14]:
arr = np.array([1, 2, 3, 3, 5, 3, 5, 3, 3, 3, 2])
arr

array([1, 2, 3, 3, 5, 3, 5, 3, 3, 3, 2])

In [15]:
np.bincount(arr).argmax()

3

#### - Combining a one and a two-dimensional NumPy Array 

In [16]:
arr_1d = np.arange(3)
arr_1d

array([0, 1, 2])

In [17]:
arr_2d = np.arange(9).reshape(3,3)
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
for n, m in np.nditer([arr_1d, arr_2d]):
    print(f'{n}:{m}')

0:0
1:1
2:2
0:3
1:4
2:5
0:6
1:7
2:8


#### - How to build an array of all combinations of two NumPy arrays? 

In [19]:
arr_1 = np.array([2, 4])
arr_2 = np.array([3, 5])

In [20]:
comb_arr = np.array(np.meshgrid(arr_1, arr_2)).T
comb_arr.reshape(-1, 2)

array([[2, 3],
       [2, 5],
       [4, 3],
       [4, 5]])

In [21]:
comb_arr

array([[[2, 3],
        [2, 5]],

       [[4, 3],
        [4, 5]]])

#### - How to add a border around a NumPy array?

In [22]:
arr = np.array([[1, 2], [3, 5]])
arr

array([[1, 2],
       [3, 5]])

In [23]:
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 5, 0],
       [0, 0, 0, 0]])

#### - How to compare two NumPy arrays?

In [24]:
arr_1 = np.array([[2, 5], [6, 2]])
arr_2 = np.array([[2, 5], [6, 2]])
  
equal_arrays = (arr_1 == arr_2).all()
equal_arrays

True

#### - How to check whether specified values are present in NumPy array?

In [25]:
arr = np.array([[2, 5, 0], [1, 2, 4]])
arr

array([[2, 5, 0],
       [1, 2, 4]])

In [26]:
print(2 in arr)
print(0 in arr)
print(6 in arr)
print(50 in arr)
print(10 in arr)

True
True
False
False
False


#### - How to get all 2D diagonals of a 3D NumPy array?

In [27]:
arr_3d = np.arange(3 * 4 * 4).reshape(3, 4, 4)
arr_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [28]:
diag_arr = np.diagonal(arr_3d,  axis1 = 1, axis2 = 2)
diag_arr

array([[ 0,  5, 10, 15],
       [16, 21, 26, 31],
       [32, 37, 42, 47]])

#### - Flatten a Matrix in Python using NumPy 

In [29]:
m = np.matrix([[1,2], [3,4]])
m

matrix([[1, 2],
        [3, 4]])

In [30]:
flat_m = m.flatten()
flat_m

matrix([[1, 2, 3, 4]])

#### - Flatten a 2d numpy array into 1d array

In [31]:
arr = np.array([[1, 2, 3], [2, 4, 5]])
arr

array([[1, 2, 3],
       [2, 4, 5]])

In [32]:
result = arr.flatten()
result

array([1, 2, 3, 2, 4, 5])

#### - Move axes of an array to new positions 

In [33]:
arr = np.zeros((3, 4, 5))
arr.shape

(3, 4, 5)

In [34]:
np.moveaxis(arr, 0, -1).shape

(4, 5, 3)

#### - NumPy – Fibonacci Series using Binet Formula

In [35]:
arr = np.arange(1, 15)
lenArr = len(arr)

sqrt = np.sqrt(5)
alpha = (1 + sqrt) / 2
beta = (1 - sqrt) / 2

Fn = np.rint(((alpha ** arr) - (beta ** arr)) / (sqrt))

print("The first {} numbers are {} . ".format(lenArr, Fn))

The first 14 numbers are [  1.   1.   2.   3.   5.   8.  13.  21.  34.  55.  89. 144. 233. 377.] . 


#### - Counts the number of non-zero values in the array 

In [36]:
arr = np.array([2, 1, 5, 0, 10, 0, 8, 0, 5, 0])
arr

array([ 2,  1,  5,  0, 10,  0,  8,  0,  5,  0])

In [37]:
count = np.count_nonzero(arr)
count

6

#### - Count the number of elements along a given axis 

In [38]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
#x-axis
print(np.size(arr, 0))

#y-axis
print(np.size(arr, 1))

2
4


#### - Trim the leading and/or trailing zeros from a 1-D array

In [40]:
arr = np.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0))
arr

array([ 0,  0,  0,  0,  1,  5,  7,  0,  6,  2,  9,  0, 10,  0,  0])

In [41]:
np.trim_zeros(arr)

array([ 1,  5,  7,  0,  6,  2,  9,  0, 10])

#### - Change data type of given numpy array

In [42]:
arr = np.array([5, 10, 15, 20, 25])

print(arr)
print(arr.dtype)

[ 5 10 15 20 25]
int32


In [43]:
arr = arr.astype('float64')

print(arr)
print(arr.dtype)

[ 5. 10. 15. 20. 25.]
float64


#### - Reverse a numpy array 

In [44]:
ini_arr = np.array([1, 2, 3, 4, 5])
ini_arr

array([1, 2, 3, 4, 5])

In [45]:
res = ini_arr[::-1]
res

array([5, 4, 3, 2, 1])

#### - How to make a NumPy array read-only? 

In [46]:
arr = np.zeros(11)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
arr[2] = 2
arr

array([0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
arr.flags.writeable = False

# arr[1] = 3

## Questions on NumPy Matrix

#### - Get the maximum value from given matrix

In [49]:
m = np.matrix(np.arange(16).reshape((4, 4)))
m

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [50]:
m.max()

15

#### - Get the minimum value from given matrix

In [51]:
m = np.matrix(np.arange(16).reshape((4, 4)))
m

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [52]:
m.min()

0

#### - Find the number of rows and columns of a given matrix using NumPy

In [53]:
m = np.matrix(np.arange(16).reshape((4, 4)))
m

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [54]:
m.shape

(4, 4)

#### - Select the elements from a given matrix

In [55]:
m = np.matrix(np.arange(16).reshape((4, 4)))
m

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [56]:
# Returns the rows you want
m[[0,1,3], :]

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [12, 13, 14, 15]])

#### - Find the sum of values in a matrix

In [57]:
m = np.matrix(np.arange(16).reshape((4, 4)))
m

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [58]:
m.sum()

120

#### - Calculate the sum of the diagonal elements of a NumPy array

In [59]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
trace = np.trace(arr)
trace

15

#### - Adding and Subtracting Matrices in Python 

In [61]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])

In [62]:
np.add(A, B)

array([[ 5,  7],
       [ 9, 11]])

In [63]:
np.subtract(A, B)

array([[-3, -3],
       [-3, -3]])

#### - Ways to add row/columns in numpy array

In [64]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
add = np.array([1, 2, 3])

result = np.hstack((arr, np.atleast_2d(add).T))
result

array([[1, 2, 3, 1],
       [4, 5, 6, 2],
       [7, 8, 9, 3]])

#### - Matrix Multiplication in NumPy

In [66]:
m_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m_2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

res = np.dot(m_1, m_2)
res

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

#### - Get the eigen values of a matrix

In [67]:
m = np.array([[1, 2], [2, 3]])
m

array([[1, 2],
       [2, 3]])

In [68]:
eigenvalues, eigenvectors = np.linalg.eig(m)

eigenvalues

array([-0.23606798,  4.23606798])

#### - How to Calculate the determinant of a matrix using NumPy?

In [69]:
m = np.array([[10, 2], [9, 4]])
m

array([[10,  2],
       [ 9,  4]])

In [70]:
det = np.linalg.det(m)
int(det)

22

#### - How to inverse a matrix using NumPy 

In [71]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
np.linalg.inv(m)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

#### - How to count the frequency of unique values in NumPy array?

In [73]:
arr = np.array([5, 10, 5, 20, 12, 2, 7, 2, 10])

uni, freq = np.unique(arr, return_counts = True)

print("Unique Values:", uni)
print("Frequency Values:", freq)

Unique Values: [ 2  5  7 10 12 20]
Frequency Values: [2 2 1 2 1 1]


#### - Multiply matrices of complex numbers using NumPy in Python 

In [74]:
m = np.array([[2+3j, 4+5j], [4+5j, 6+7j]])
n = np.array([[8+7j, 5+6j], [9+10j, 1+2j]])

print(m)
print()
print(n)

[[2.+3.j 4.+5.j]
 [4.+5.j 6.+7.j]]

[[8. +7.j 5. +6.j]
 [9.+10.j 1. +2.j]]


In [75]:
resp = np.vdot(m, n)
print(resp)


(193-11j)


#### - Compute the outer product of two given vectors using NumPy in Python

In [76]:
m_1 = np.array([[1, 2], [3, 4]])
m_2 = np.array([[0, 1], [2, 5]])

print(m_1)
print()
print(m_2)

[[1 2]
 [3 4]]

[[0 1]
 [2 5]]


In [77]:
result = np.outer(m_1, m_2)
result

array([[ 0,  1,  2,  5],
       [ 0,  2,  4, 10],
       [ 0,  3,  6, 15],
       [ 0,  4,  8, 20]])

#### - Calculate inner, outer, and cross products of matrices and vectors using NumPy

In [78]:
arr_a = np.array([1, 2])
arr_b = np.array([3, 4])
print("Vectors :")
print("a = ", arr_a)
print("b = ", arr_b)

print("\nInner : ", np.inner(arr_a, arr_b))
print("\nOuter : ", np.outer(arr_a, arr_b))
print("\nCross : ", np.cross(arr_a, arr_b))

Vectors :
a =  [1 2]
b =  [3 4]

Inner :  11

Outer :  [[3 4]
 [6 8]]

Cross :  -2


In [79]:
m_a = np.array([[6, 3, 4], [3, 2, 4]])
m_b = np.array([[1, 8, 0], [7, 10, 3]])
print("\nMatrices :")
print("a =", m_a)
print("b =", m_b)

print("\nInner : ", np.inner(m_a, m_b))
print("\nOuter : ", np.outer(m_a, m_b))
print("\nCross : ", np.cross(m_a, m_b))


Matrices :
a = [[6 3 4]
 [3 2 4]]
b = [[ 1  8  0]
 [ 7 10  3]]

Inner :  [[30 84]
 [19 53]]

Outer :  [[ 6 48  0 42 60 18]
 [ 3 24  0 21 30  9]
 [ 4 32  0 28 40 12]
 [ 3 24  0 21 30  9]
 [ 2 16  0 14 20  6]
 [ 4 32  0 28 40 12]]

Cross :  [[-32   4  45]
 [-34  19  16]]


#### - Compute the covariance matrix of two given NumPy arrays

In [80]:
array1 = np.array([2, 1, 1, 4])
array2 = np.array([2, 2, 1, 1])

print(array1)
print()
print(array2)

[2 1 1 4]

[2 2 1 1]


In [81]:
covariance = np.cov(array1, array2)
print("\nCovariance: \n", covariance)


Covariance: 
 [[ 2.         -0.33333333]
 [-0.33333333  0.33333333]]


#### - Convert covariance matrix to correlation matrix using Python 

#### - Compute the Kronecker product of two mulitdimension NumPy arrays


In [83]:
arr_1 = np.array([[1, 2], [3, 4]])
arr_2 = np.array([[5, 6], [7, 8]])

print(arr_1)
print()
print(arr_2)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [84]:
kroneckerProduct = np.kron(arr_1, arr_2)
print(kroneckerProduct)

[[ 5  6 10 12]
 [ 7  8 14 16]
 [15 18 20 24]
 [21 24 28 32]]


#### - Convert the matrix into a list

In [85]:
m = np.matrix(np.arange(9).reshape((3,3)))
m

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [86]:
m.tolist()

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

## Questions on NumPy Indexing

#### - Replace NumPy array elements that doesn’t satisfy the given condition

In [87]:
arr = np.array([65.315, 38.8583, 15.763])
arr

array([65.315 , 38.8583, 15.763 ])

In [88]:
arr[arr > 30.] = 15.50
arr

array([15.5  , 15.5  , 15.763])

#### - Return the indices of elements where the given condition is satisfied

In [89]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
condition = np.where(arr < 4)

arr[condition]

array([1, 2, 3])

#### - Replace NaN values with average of columns

In [91]:
arr = np.array([[1.3, 2.5, 3.6, np.nan], [2.6, 3.3, np.nan, 5.5], [2.1, 3.2, 5.4, 6.5]])
arr

array([[1.3, 2.5, 3.6, nan],
       [2.6, 3.3, nan, 5.5],
       [2.1, 3.2, 5.4, 6.5]])

In [92]:
mean = np.nanmean(arr, axis = 0)
inds = np.where(np.isnan(arr))

arr[inds] = np.take(mean, inds[1])

arr

array([[1.3, 2.5, 3.6, 6. ],
       [2.6, 3.3, 4.5, 5.5],
       [2.1, 3.2, 5.4, 6.5]])

#### - Replace negative value with zero in numpy array 

In [93]:
arr = np.array([1, -2, 3, 4, -5, -6])
arr

array([ 1, -2,  3,  4, -5, -6])

In [94]:
arr[arr < 0] = 0
arr

array([1, 0, 3, 4, 0, 0])

#### - How to get values of an NumPy array at certain index positions?

In [95]:
arr = np.array([1, 2, 3, 4, 5])

print(arr[0: 2])
print(arr[-1])

[1 2]
5


#### - Find indices of elements equal to zero in a NumPy array

In [96]:
arr = np.array([1, 2, 0, 4, 0, 5, 0, 7, 8, 0, 9, 0, 10])
arr

array([ 1,  2,  0,  4,  0,  5,  0,  7,  8,  0,  9,  0, 10])

In [97]:
res = np.where(arr == 0)[0]
res

array([ 2,  4,  6,  9, 11], dtype=int64)

#### - How to Remove columns in Numpy array that contains non-numeric values?

In [98]:
arr = np.array([[8, 21, np.nan], [np.nan, 5, np.nan]])
arr

array([[ 8., 21., nan],
       [nan,  5., nan]])

In [99]:
arr[:, ~np.isnan(arr).any(axis=0)]

array([[21.],
       [ 5.]])

#### - How to access different rows of a multidimensional NumPy array?

In [100]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [101]:
res_arr = arr[[0,2]]
res_arr

array([[10, 20, 30],
       [70, 80, 90]])

#### - Get row numbers of NumPy array having element larger than X 

In [102]:
arr = np.array([[0, 2, 2, 4, 8], [6, -5, 0, 0, -5], [2, 1, 5, -25, 6], [52, 0, 65, -35, 0]])
arr

array([[  0,   2,   2,   4,   8],
       [  6,  -5,   0,   0,  -5],
       [  2,   1,   5, -25,   6],
       [ 52,   0,  65, -35,   0]])

In [103]:
X = 6

output = np.where(np.any(arr > X, axis = 1))
output

(array([0, 3], dtype=int64),)

#### - Get filled the diagonals of NumPy array

In [104]:
arr = np.array([[1, 2], [3, 4]])
arr

array([[1, 2],
       [3, 4]])

In [105]:
np.fill_diagonal(arr, 5)

arr

array([[5, 2],
       [3, 5]])

#### - Check elements present in the NumPy array

In [106]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
print(1 in arr)
print(0 in arr)
print(5 in arr)
print(10 in arr)
print(3 in arr)

True
False
True
False
True


#### - Combined array index by index 

In [108]:
arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6]])

print(arr_a)
print()
print(arr_b)

[[1 2]
 [3 4]]

[[5 6]]


In [109]:
np.concatenate((arr_a, arr_b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])


## Questions on NumPy Linear Algebra 

#### - Find a matrix or vector norm using NumPy 

In [111]:
vector = np.arange(10)

vec_norm = np.linalg.norm(vector)
vec_norm

16.881943016134134

#### - Calculate the QR decomposition of a given matrix using NumPy 

In [113]:
m = np.array([[1, 2, 3], [3, 4, 5]])
m

array([[1, 2, 3],
       [3, 4, 5]])

In [115]:
q, r = np.linalg.qr(m)

print('Q:\n', q)
print('\nR:\n', r)

Q:
 [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]

R:
 [[-3.16227766 -4.42718872 -5.69209979]
 [ 0.         -0.63245553 -1.26491106]]


#### - Compute the condition number of a given matrix using NumPy

In [118]:
m = np.array([[1, 2], [3, 4]])
m

array([[1, 2],
       [3, 4]])

In [119]:
res = np.linalg.cond(m)
res

14.933034373659265

#### - Compute the eigenvalues and right eigenvectors of a given square array using NumPy?

In [120]:
m = np.array([[1, 2], [2, 3]])
m

array([[1, 2],
       [2, 3]])

In [124]:
w, v = np.linalg.eig(m)

print("Eigen values:\n", w)
print("Right eigenvectors:\n", v)

Eigen values:
 [-0.23606798  4.23606798]
Right eigenvectors:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


#### - Calculate the Euclidean distance using NumPy 

In [126]:
arr_1 = np.array((1, 2, 3))
arr_2 = np.array((1, 1, 1))

dist = np.linalg.norm(arr_1 - arr_2)
dist

2.23606797749979

## Questions on NumPy Random 

#### - Create a Numpy array with random values 

In [132]:
from numpy.random import seed
from numpy.random import randint

# seed random number generator
seed(1)

values = randint(0, 8, 10)
values

array([5, 3, 4, 0, 7, 1, 3, 5, 7, 0])

#### - How to choose elements from the list with different probability using NumPy? 

In [137]:
import numpy as np

list_t = [1, 2, 3, 4, 5]

number = np.random.choice(list_t)
number

2

#### - How to get weighted random choice in Python?

In [145]:
import random

list_t = [10, 20, 30, 40, 50]

randomList = random.choices(list_t, weights=(1, 2, 3, 4, 5), k=5)
randomList

[30, 50, 20, 10, 30]

#### - Generate Random Numbers From The Uniform Distribution using NumPy

In [146]:
import numpy as np

res = np.random.uniform(size=4)
res

array([0.53881673, 0.41919451, 0.6852195 , 0.20445225])

#### - Get Random Elements form geometric distribution

#### - Get Random elements from Laplace distribution

#### - Return a Matrix of random values from a uniform distribution

In [152]:
import numpy as geek
import numpy.matlib

res = geek.matlib.rand((3, 4))
res

matrix([[0.53158347, 0.67921295, 0.51287514, 0.29911234],
        [0.10538467, 0.28493215, 0.76885285, 0.6407827 ],
        [0.8013307 , 0.51712053, 0.23210002, 0.62796193]])

#### - Return a Matrix of random values from a Gaussian distribution

##  Questions on NumPy Sorting and Searching

#### - How to get element-wise true division of an array using Numpy?

In [153]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [154]:
res = np.true_divide(arr, 4)
res

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

#### - How to calculate the element-wise absolute value of NumPy array?

In [155]:
arr = np.array([1, -2, 3])
arr

array([ 1, -2,  3])

In [156]:
res = np.absolute(arr)
res

array([1, 2, 3])

#### - Compute the negative of the NumPy array 

In [160]:
arr = np.array([[3, -7, 5], [-6, 2, 1]])
arr

array([[ 3, -7,  5],
       [-6,  2,  1]])

In [161]:
out_arr = np.negative(arr)
out_arr

array([[-3,  7, -5],
       [ 6, -2, -1]])

#### - Multiply 2d numpy array corresponding to 1d array


In [165]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2 = np.array([0, 2, 3])

print(arr_1)
print()
print(arr_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[0 2 3]


In [167]:
result = arr_1 * arr_2[:, np.newaxis]
result

array([[ 0,  0,  0],
       [ 8, 10, 12],
       [21, 24, 27]])

#### - Computes the inner product of two arrays

In [169]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([0,1,0])
np.inner(arr_1, arr_2)

2

#### - Compute the nth percentile of the NumPy array

In [171]:
arr = np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [172]:
print("50th: ", np.percentile(arr, 50))
print("25th: ", np.percentile(arr, 25))
print("75th: ",np.percentile(arr, 75))

50th:  4.0
25th:  2.5
75th:  5.5


#### - Calculate the n-th order discrete difference along the given axis

#### - Calculate the sum of all columns in a 2D NumPy array 

In [177]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [178]:
arr.sum(axis=0)

array([5, 7, 9])

#### - Calculate average values of two given NumPy arrays

In [179]:
arr1 = np.array([3, 4])
arr2 = np.array([1, 0])

avg = (arr1 + arr2) / 2
avg

array([2., 2.])

#### - How to compute numerical negative value for all elements in a given NumPy array?

In [180]:
arr = np.array([-1, -2, -3, 1, 2, 3, 0])
arr

array([-1, -2, -3,  1,  2,  3,  0])

In [181]:
np.negative(arr)

array([ 1,  2,  3, -1, -2, -3,  0])

#### - How to get the floor, ceiling and truncated values of the elements of a numpy array?

In [185]:
arr = np.array([-1, 2, 3, 4, 5])
arr

array([-1,  2,  3,  4,  5])

In [186]:
np.floor(arr)

array([-1.,  2.,  3.,  4.,  5.])

In [187]:
np.ceil(arr)

array([-1.,  2.,  3.,  4.,  5.])

In [188]:
np.trunc(arr)

array([-1.,  2.,  3.,  4.,  5.])

#### - How to round elements of the NumPy array to the nearest integer? 

In [192]:
arr = np.array([0.2, 0.3, 0.4, 0.5, 0.6, 0.7])
arr

array([0.2, 0.3, 0.4, 0.5, 0.6, 0.7])

In [193]:
np.rint(arr)

array([0., 0., 0., 0., 1., 1.])

#### - Find the round off the values of the given matrix 

In [197]:
arr = np.array([[1.3, 2.5, 3.8], [4, 5.1, 6.2], [7.4, 8.6, 9]])
arr

array([[1.3, 2.5, 3.8],
       [4. , 5.1, 6.2],
       [7.4, 8.6, 9. ]])

In [198]:
arr.round()

array([[1., 2., 4.],
       [4., 5., 6.],
       [7., 9., 9.]])

#### - Determine the positive square-root of an array 

In [200]:
arr = np.sqrt([1, 4, 9, 16])
arr

array([1., 2., 3., 4.])

#### - Evaluate Einstein’s summation convention of two multidimensional NumPy arrays 

In [202]:
m1 = np.array([[1, 2], [0, 2]])
m2 = np.array([[0, 1], [3, 4]])

print(m1)
print()
print(m2)

[[1 2]
 [0 2]]

[[0 1]
 [3 4]]


In [203]:
res = np.einsum("mk,kn", m1, m2)
res

array([[6, 9],
       [6, 8]])

## Questions on NumPy Statistics 

#### - Compute the median of the flattened NumPy array 

In [204]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [205]:
np.median(arr)

4.0

#### - Find Mean of a List of Numpy Array 

In [207]:
arr_list = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]
arr_list

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [208]:
res = []
for i in range(len(arr_list)):
    res.append(np.mean(arr_list[i]))

res

[2.0, 5.0, 8.0]

#### - Calculate the mean of array ignoring the NaN value 

In [212]:
arr = np.array([[2, 5, 37], [7, 13, np.nan]])
arr

array([[ 2.,  5., 37.],
       [ 7., 13., nan]])

In [213]:
np.nanmean(arr)

12.8

#### - Get the mean value from given matrix 

In [214]:
m = np.matrix(np.arange(12).reshape((3, 4)))
m

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [215]:
m.mean()

5.5

#### - Compute the variance of the NumPy array 

In [217]:
arr = [52, 5, 7, 51, 4]

np.var(arr)

512.5600000000001

#### - Compute the standard deviation of the NumPy array 

In [219]:
arr = [52, 5, 7, 51, 4]

np.std(arr)

22.639787984873003

#### - Compute pearson product-moment correlation coefficients of two given NumPy arrays 

In [220]:
arr_1 = np.array([0, 1, 2])
arr_2 = np.array([3, 4, 5])

res = np.corrcoef(arr_1, arr_2)
res

array([[1., 1.],
       [1., 1.]])

#### - Calculate the mean across dimension in a 2D NumPy array 

#### - Calculate the average, variance and standard deviation in Python using NumPy 

In [225]:
arr = np.array([21, 2, 4, 5, 5, 8, 7, 4])

print(np.average(arr))
print(np.var(arr))
print(np.std(arr))

7.0
31.0
5.5677643628300215


#### - Describe a NumPy Array in Python 

In [226]:
arr = np.array([21, 2, 4, 5, 5, 8, 7, 4])

print("Array =", arr)
print("Mean =", np.mean(arr))
print("Median =", np.median(arr))

Array = [21  2  4  5  5  8  7  4]
Mean = 7.0
Median = 5.0


## Questions on Polynomial

#### - Define a polynomial function 

#### - How to add one polynomial to another using NumPy in Python? 

In [229]:
from numpy.polynomial import polynomial as P

c1 = (2,5,3)
c2 = (3,2,1)

P.polyadd(c1,c2)

array([5., 7., 4.])

#### - How to subtract one polynomial to another using NumPy in Python? 

In [230]:
c1 = (2,5,3)
c2 = (3,2,1)

P.polysub(c1,c2)

array([-1.,  3.,  2.])

#### - How to multiply a polynomial to another using NumPy in Python? 

In [232]:
c1 = (2,5,3)
c2 = (3,2,1)

np.polymul(c1, c2)

array([ 6, 19, 21, 11,  3])

#### - How to divide a polynomial to another using NumPy in Python? 

In [233]:
arr_1 = np.array([3.0, 5.0, 2.0])
arr_2 = np.array([2.0, 1.0])

np.polydiv(arr_1, arr_2)

(array([1.5 , 1.75]), array([0.25]))

#### - Find the roots of the polynomials using NumPy 

In [237]:
arr = np.array([3, 2, 1])

np.roots(arr)

array([-0.33333333+0.47140452j, -0.33333333-0.47140452j])

#### - Evaluate a 2-D polynomial series on the Cartesian product 

In [239]:
from numpy.polynomial.polynomial import polygrid2d

arr = np.array([[1, 3, 5], [4, 5, 6]])

polygrid2d([7, 9], [8, 10], arr)

array([[3341., 5109.],
       [4197., 6417.]])

#### - Evaluate a 3-D polynomial series on the Cartesian product

In [240]:
from numpy.polynomial.polynomial import polygrid3d

arr = np.array([[2, 3, 4], [5, 4, 6], [15, 11, 12]])

polygrid3d([7, 9], [8, 10], [5, 6], arr)

array([[419018., 493640.],
       [637682., 751244.]])